FROM golang:1.21-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine

COPY --from=builder /app/server /server

COPY --from=builder /go/bin/dlv /dlv

EXPOSE 40000

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/server"]